name: Update Git Stats

on:
  schedule:
    # Schedule will be injected from config
    - cron: '{{ SCHEDULE }}'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Fetch Git Stats
        env:
          # Inject secrets from config
          {{#each profiles}}
          {{uppercase platform}}_TOKEN: ${{~ '{' ~}} secrets.{{tokenSecret}} {{~ '}' ~}}
          {{uppercase platform}}_USERNAME: {{username}}
          {{/each}}
        run: |
          # Create data directory
          mkdir -p {{ dataPath | dirname }}
          
          echo "Starting git stats collection..."
          
          # Initialize JSON structure
          cat > stats_temp.json << 'EOF'
{
  "lastUpdated": "",
  "profiles": [],
  "totals": {
    "projectCount": 0,
    "commitCount": 0
  },
  "metadata": {
    "fetchedAt": 0,
    "source": "github_actions"
  }
}
EOF
          
          # Array to store profile data
          PROFILES_JSON="[]"
          TOTAL_PROJECTS=0
          TOTAL_COMMITS=0
          
          {{#each profiles}}
          echo "================================================"
          echo "Fetching stats for {{username}} on {{platform}}"
          echo "================================================"
          
          {{#if (eq platform 'github')}}
          # GitHub Stats
          if [ -n "$GITHUB_TOKEN" ]; then
            echo "Fetching GitHub repositories..."
            REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/users/$GITHUB_USERNAME/repos?per_page=100")
            
            REPO_COUNT=$(echo "$REPOS" | jq 'length')
            echo "Found $REPO_COUNT repositories"
            
            # Fetch contributions (simplified - using commit count as proxy)
            COMMIT_COUNT=0
            for repo in $(echo "$REPOS" | jq -r '.[].full_name'); do
              echo "Fetching commits for $repo..."
              COMMITS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$repo/commits?per_page=100&author=$GITHUB_USERNAME")
              
              REPO_COMMITS=$(echo "$COMMITS" | jq 'length')
              COMMIT_COUNT=$((COMMIT_COUNT + REPO_COMMITS))
              sleep 1
            done
            
            echo "Total commits: $COMMIT_COUNT"
            
            # Fetch contribution graph
            CONTRIB_QUERY=$(cat <<GRAPHQL
{
  "query": "query(\$userName: String!, \$from: DateTime!, \$to: DateTime!) { user(login: \$userName) { contributionsCollection(from: \$from, to: \$to) { contributionCalendar { totalContributions weeks { contributionDays { contributionCount date weekday } firstDay } } } } }",
  "variables": {
    "userName": "$GITHUB_USERNAME",
    "from": "$(date -u -d '1 year ago' +"%Y-%m-%dT00:00:00Z")",
    "to": "$(date -u +"%Y-%m-%dT23:59:59Z")"
  }
}
GRAPHQL
            )
            
            CONTRIB_DATA=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST \
              -d "$CONTRIB_QUERY" \
              https://api.github.com/graphql)
            
            CONTRIBUTIONS=$(echo "$CONTRIB_DATA" | jq -c '.data.user.contributionsCollection.contributionCalendar.weeks')
            
            # Add to profiles array
            PROFILE_DATA=$(jq -n \
              --arg username "$GITHUB_USERNAME" \
              --arg platform "github" \
              --argjson projectCount "$REPO_COUNT" \
              --argjson commitCount "$COMMIT_COUNT" \
              --argjson contributions "$CONTRIBUTIONS" \
              '{
                username: $username,
                platform: $platform,
                stats: {
                  projectCount: $projectCount,
                  commitCount: $commitCount,
                  contributions: $contributions
                }
              }')
            
            PROFILES_JSON=$(echo "$PROFILES_JSON" | jq --argjson profile "$PROFILE_DATA" '. += [$profile]')
            TOTAL_PROJECTS=$((TOTAL_PROJECTS + REPO_COUNT))
            TOTAL_COMMITS=$((TOTAL_COMMITS + COMMIT_COUNT))
          else
            echo "No GitHub token provided, skipping..."
          fi
          {{/if}}
          
          {{#if (eq platform 'gitlab')}}
          # GitLab Stats
          if [ -n "$GITLAB_TOKEN" ]; then
            echo "Fetching GitLab projects..."
            PROJECTS=$(curl -s -H "Private-Token: $GITLAB_TOKEN" \
              "https://gitlab.com/api/v4/users/$GITLAB_USERNAME/projects?per_page=100")
            
            if echo "$PROJECTS" | jq -e 'type == "array"' > /dev/null 2>&1; then
              PROJECT_COUNT=$(echo "$PROJECTS" | jq 'length')
              echo "Found $PROJECT_COUNT projects"
              
              COMMIT_COUNT=0
              for project_id in $(echo "$PROJECTS" | jq -r '.[].id'); do
                echo "Fetching commits for project $project_id..."
                COMMITS=$(curl -s -H "Private-Token: $GITLAB_TOKEN" \
                  "https://gitlab.com/api/v4/projects/$project_id/repository/commits?per_page=100")
                
                if echo "$COMMITS" | jq -e 'type == "array"' > /dev/null 2>&1; then
                  PROJECT_COMMITS=$(echo "$COMMITS" | jq 'length')
                  COMMIT_COUNT=$((COMMIT_COUNT + PROJECT_COMMITS))
                fi
                sleep 1
              done
              
              echo "Total commits: $COMMIT_COUNT"
              
              # Add to profiles array
              PROFILE_DATA=$(jq -n \
                --arg username "$GITLAB_USERNAME" \
                --arg platform "gitlab" \
                --argjson projectCount "$PROJECT_COUNT" \
                --argjson commitCount "$COMMIT_COUNT" \
                '{
                  username: $username,
                  platform: $platform,
                  stats: {
                    projectCount: $projectCount,
                    commitCount: $commitCount
                  }
                }')
              
              PROFILES_JSON=$(echo "$PROFILES_JSON" | jq --argjson profile "$PROFILE_DATA" '. += [$profile]')
              TOTAL_PROJECTS=$((TOTAL_PROJECTS + PROJECT_COUNT))
              TOTAL_COMMITS=$((TOTAL_COMMITS + COMMIT_COUNT))
            else
              echo "GitLab API returned an error"
              echo "$PROJECTS" | head -n 5
            fi
          else
            echo "No GitLab token provided, skipping..."
          fi
          {{/if}}
          
          {{/each}}
          
          echo "================================================"
          echo "Generating final JSON file..."
          echo "================================================"
          
          # Build final JSON
          jq -n \
            --arg lastUpdated "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --argjson profiles "$PROFILES_JSON" \
            --argjson totalProjects "$TOTAL_PROJECTS" \
            --argjson totalCommits "$TOTAL_COMMITS" \
            --argjson fetchedAt "$(date +%s)000" \
            '{
              lastUpdated: $lastUpdated,
              profiles: $profiles,
              totals: {
                projectCount: $totalProjects,
                commitCount: $totalCommits
              },
              metadata: {
                fetchedAt: $fetchedAt,
                source: "github_actions"
              }
            }' > {{ dataPath }}
          
          echo "Stats saved to {{ dataPath }}"
          
      - name: Format with Prettier
        run: |
          npm install
          npx prettier --write {{ dataPath }}
          
      - name: Show generated file
        run: |
          echo "Generated git stats:"
          cat {{ dataPath }}
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code {{ dataPath }} || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add {{ dataPath }}
          git commit -m "chore: update git stats [skip ci]"
          git push
          
      - name: No changes detected
        if: steps.git-check.outputs.changed != 'true'
        run: echo "No changes in git stats"